### ISSUE TITLE
Can't load dll

### ISSUE THREAD

**Issue by ghost** [DestroyerDarkNess/Udrakoloader#1]
At first thank for your great project.
As I'm not good at c++, this is good for me.

And sorry if this dumb question.
I'm trying to load my dll(c#) file into my game, Monster Hunter Frontier(it's dead game, running on private server).
I downloaded Udrakoloader.dll and renamed it to Udrakoloader.asi to load with Ultimate ASI loader (https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases).
Then placed my dll inside Udrakoloader folder.
Then I use x32dbg(a debugger) to check if the game loads what dll.
I can confirm Udrakoloader.asi is loaded but my dll is not loaded.
Am I wrong something?

**Comment by DestroyerDarkNess** [comment]
Hi, This project was good at the time, but it's outdated now, I have better projects so you can load your .NET-made dll in target processes.

**In any case, what you need is to use :**

[DestroyerDarkNess/NETBuilderInjection](https://github.com/DestroyerDarkNess/NETBuilderInjection)

If you need help, you can talk to my discord: **Destroyer#8328**

**Comment by ghost** [comment]
Thank you for quick response.
I'll take a look that.
